//N.B. This example serves to show that running QCModAffine
//directly does not work since there are non-trivial
//height contributions

load "src/StarQuotientMeasures.m";
load "src/rank.m";
SetPath("QCMod");
load "qc_modular.m";
load "divisor_heights.m";
load "qc_init_g2.m";
load "howe_zhu.m";
SetPath("QCMod");
load "ModularCurvesX0plusG4-6/model_equation_finder.m";
load "src/misc.m";

//SetDebugOnError(true);

N := 187;
ALs := [11, 17];
seq_al := ALs;

X187star := X0NQuotient(N, ALs);
pts := PointSearch(X187star, 30);
// Ambient projective space
P<X, Y, Z> := ProjectiveSpace(Rationals(), 2);

/*S, Q, model_map, pts187, good_primes, inf_pts, bad_pts :=
find_and_test_model(-Z,Y+Z, Y+Z, X+Y+Z, X187star, x, y, pts);
good_primes;
//[31]
Q;
primes := [31]; // TODO

SetMemoryLimit(10 * 1024^3);*/
 L1:=X + Y + 2*Z;
 L2:=2*X - 2*Y + Z;
 L3:=Y - Z;
 L4:=-2*X + 2*Y - Z;

S, Q, model_map, pts187, good_primes, inf_pts, bad_pts :=
                        find_and_test_model(L1, L2, L3, L4, X187star, x, y, pts
: printlevel:=1);

primes := [37];
exponents := [Integers()| 1 : i in [1..#primes]]; // TODO


J := JZero(N);
if #seq_al gt 0 then
    J_quo := Image(&*[1+AtkinLehnerOperator(J,i) : i in ALs]);
else
    J_quo := J;
end if;
J := J_quo;
gX := Dimension(J);
printf "genus = %o\n", gX;
assert rank_quo(N, ALs) eq gX; // check QC condition

ptsX := PointSearch(S, 30); // projective coordinates
// First compute local heights of representatives for generators of J(Q) tensor Q at p. 
index_of_base_point := [i : i in [1..#ptsX] | ptsX[i,3] ne 0][1]; // first index of ptsX such that the z-coordinate is non-zero
assert ptsX[index_of_base_point,3] ne 0;
//base_pt := [ptsX[index_of_base_point,1]/ptsX[index_of_base_point,3], ptsX[index_of_base_point,2]/ptsX[index_of_base_point,3]^(gX+1)]; 
base_pt := [ptsX[index_of_base_point,1]/ptsX[index_of_base_point,3], ptsX[index_of_base_point,2]/ptsX[index_of_base_point,3]]; 
printf "Using base point %o.\n", base_pt;

// check that differences of ptsX generate a subgroup of rank gX of J(Q)
//torsion_bas, torsion_orders, bas, mMW := generators(J);
//assert #bas eq gX; // rank = 2
torsionMultiple := TorsionMultiple(J);
printf "#J(Q)_tors divides %o.\n", torsionMultiple;
assert torsionMultiple eq 1;

X := S;

// if ([J(Q) : <differences of points>], M) = 1, we can use the differrences as divisors, spliting indices [1,0,...0] and so on and torsion_bas = []

/*// find a finite index subgroup (generated by divisors) of J(Q) given by differences of P in C(Q), and writes them in the basis bas of J(Q) (splitting_indices)
function divisors_from_curve(X)
  divisors_found := [];
  splitting_indices_found := [];
  indices_found := [];
  index := 0;
  for P1P2 in Subsets({P : P in ptsX}, 2) do
    P1, P2 := Explode(Setseq(P1P2));
    if 0 in {P1[3], P2[3]} then // exclude the case where one point is at infinity
      continue;
    end if;
    for Q1Q2 in Subsets({P : P in ptsX}, 2) do
      Q1, Q2 := Explode(Setseq(Q1Q2));
      if 0 in {Q1[3], Q2[3]} or P1P2 eq Q1Q2 then // exclude the case where one point is at infinity
        continue;
      end if;
      divisors := [* [* [[P1[1]/P1[3],P1[2]/P1[3]^(gX+1)]], [[P2[1]/P2[3],P2[2]/P2[3]^(gX+1)]] *],
                     [* [[Q1[1]/Q1[3],Q1[2]/Q1[3]^(gX+1)]], [[Q2[1]/Q2[3],Q2[2]/Q2[3]^(gX+1)]] *]*];
      D1 := P1 - P2; // in J(Q)
      D2 := Q1 - Q2;
      splitting_generators := [D1, D2];
      
      D1_in_MW := D1 @@ mMW;
      D2_in_MW := D2 @@ mMW;
      splitting_indices := [Eltseq(D1_in_MW)[#torsion_bas+1..#torsion_bas+gX], Eltseq(D2_in_MW)[#torsion_bas+1..#torsion_bas + #bas]]; // D1, D2 in bas.i
      
      // compute the index of the span of divisors in the MW group
      index := Index(Domain(mMW), sub< Domain(mMW) | [D1_in_MW, D2_in_MW] >);
      if index ne 0 then
        Append(~divisors_found, divisors);
        Append(~splitting_indices_found, splitting_indices);
        Append(~indices_found, index);
      end if;
      if index eq &*torsion_orders then // we found the whole free part of the MW group
        break;
      end if;
    end for;
    if index eq &*torsion_orders then
      break;
    end if;
  end for;
  // take the configuration with minimal finite index
  min, pos := Minimum(indices_found);
  assert min gt 0;
  divisors := divisors_found[pos];
  splitting_indices := splitting_indices_found[pos];
  printf "Use independent points %o\n", divisors;
  printf "splitting indices: %o\n", splitting_indices;
  printf "index in J(Q): %o\n", min;
  return divisors, splitting_indices;
end function;

divisors, splitting_indices := divisors_from_curve(X);*/
// TODO: check G/M = J(Q)/M
pts := [ptsX[i] : i in [1..#ptsX] | i ne index_of_base_point];
base_point := ptsX[index_of_base_point];
//divisors := [* [* [[P[1]/P[3],P[2]/P[3]^(gX+1)]], [[base_point[1]/base_point[3],base_point[2]/base_point[3]^(gX+1)]] *]
//                    : P in pts *];
divisors := [* [* [[P[1]/P[3],P[2]/P[3]]], [[base_point[1]/base_point[3],base_point[2]/base_point[3]]] *]
                    : P in pts *];
assert gX eq 3;
assert torsionMultiple eq 1;
splitting_indices := [ [1,0,0], [0,1,0], [0,0,1] ];

X := Curve(P, DefiningEquations(S)[1]);
printf "%o known points beside base point.\n", #pts;
bases := SetToSequence(Subsets({[Eltseq(pt), Eltseq(base_point)] : pt in pts}, gX)); // TODO: assumes we have a free generating set

function clear_denominators(seq)
  d := LCM([Denominator(s) : s in seq]);
  return [d*s : s in seq];
end function;

function reduction_homomorphism(C, bas, M, ps)
  Gamma := FreeAbelianGroup(#bas);
  JpMs := [];
  imbases := [* *];
  redJMs := [* *];
  for p in ps do
    Cp := BaseChange(C, Bang(Rationals(), GF(p)));
    Jp, _, DL := ClassGroup(Cp);
    Jp := TorsionSubgroup(Jp);
    JpM, quot := quo<Jp | M*Jp>;
    red := func<pt | Place(Cp!ChangeUniverse(clear_denominators(Eltseq(pt)), GF(p)))>;
    imbas := [quot(DL(red(b[1]) - red(b[2]))) : b in bas];
    redJM := hom<Gamma -> JpM | imbas>;
    ker := Kernel(redJM);
    printf "p = %o: im = %o, exp(%o) = %o\n", p, AbelianInvariants(Image(redJM)), AbelianInvariants(quo<ker | M*Gamma>), Exponent(quo<ker | M*Gamma>);
    Append(~JpMs, JpM);
    Append(~imbases, imbas);
    Append(~redJMs, redJM);
  end for;
  JpM, inclusions := DirectProduct(JpMs);
  return hom<Gamma -> JpM | [&+[inclusions[j](imbases[j][i]) : j -> p in ps] : i in [1..#bas]]>, redJMs;
end function;

function compute_d(C, bas, M, ps)
  redJM, redJMs := reduction_homomorphism(C, bas, M, ps);
  Gamma := Domain(redJM);
  JM := Codomain(redJM);
  im := Image(redJM);
  ranks := [];
  for q in PrimeDivisors(M) do
    rank := #AbelianInvariants(quo<JM | q*JM>);
    printf "q = %o: rank(im/q) = %o\n", q, rank;
    Append(~ranks, rank);
  end for;
  ker := Kernel(redJM);
  _, quot := quo<Gamma | M*Gamma>;
  print AbelianInvariants(quot(ker));
  d := Exponent(quot(ker));
  //ker := &meet[Kernel(red) : red in redJMs];
  //print AbelianInvariants(quot(ker));
  return d, ranks;
end function;

exponents := [3];
qc_M := &*[primes[i]^exponents[i] : i in [1..#primes]];  // modulus
M := qc_M;
aux_int := 2^5;

/*
p := 4127;
Cp := BaseChange(X, Bang(Rationals(), GF(p)));
Jp, _, DL := ClassGroup(Cp);
Jp := TorsionSubgroup(Jp);
print Jp; // Z/67963257526 = 37^3 * ...*/

M := M * aux_int;
// all p with J(F_p)/37 of rank > 0
// comment out p that don't eliminate cosets
mws_primes := [2, 29, 157, 401, 463, 587, 617, 691, 757, 823, 1033, 1439, 3617, 4127];
// all p with J(F_p)/2 of rank > 0
mws_primes cat:= [7, 13, 19, 41, 43, 47, 53, 61, 83, 103, 127, 131, 163, 173, 199, 211, 233];

mws_primes := Sort(mws_primes);

// all p < 10000 with gcd(p, 2 * 37) != 1
//mws_primes := [2, 7, 13, 19, 29, 41, 43, 47, 53, 61, 73, 79, 83, 101, 103, 107, 109, 127, 131, 139, 149, 151, 157, 163, 167, 173, 193, 197, 199, 211, 227, 233, 239, 241, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 337, 347, 349, 359, 373, 397, 401, 409, 419, 421, 431, 439, 457, 461, 463, 479, 491, 499, 503, 523, 541, 547, 557, 563, 569, 571, 587, 593, 599, 601, 607, 613, 617, 659, 673, 677, 683, 691, 701, 733, 739, 743, 757, 761, 769, 773, 787, 809, 811, 821, 823, 827, 853, 857, 863, 877, 883, 887, 907, 911, 919, 929, 937, 941, 953, 967, 991, 997, 1009, 1019, 1021, 1031, 1033, 1051, 1063, 1069, 1087, 1091, 1097, 1109, 1117, 1123, 1129, 1151, 1163, 1181, 1187, 1193, 1201, 1217, 1223, 1229, 1231, 1237, 1249, 1283, 1289, 1291, 1297, 1307, 1319, 1327, 1361, 1367, 1381, 1399, 1427, 1429, 1433, 1439, 1447, 1451, 1453, 1459, 1471, 1481, 1483, 1487, 1493, 1531, 1543, 1549, 1553, 1559, 1567, 1571, 1579, 1583, 1597, 1601, 1609, 1613, 1619, 1621, 1627, 1657, 1663, 1667, 1669, 1693, 1697, 1699, 1723, 1733, 1753, 1759, 1777, 1789, 1801, 1811, 1823, 1847, 1861, 1867, 1873, 1877, 1889, 1907, 1913, 1931, 1933, 1949, 1979, 1987, 1993, 1997, 1999, 2003, 2039, 2053, 2063, 2069, 2081, 2087, 2089, 2111, 2113, 2129, 2131, 2141, 2153, 2203, 2207, 2213, 2221, 2237, 2239, 2243, 2251, 2269, 2273, 2287, 2309, 2333, 2339, 2351, 2371, 2381, 2383, 2389, 2393, 2411, 2417, 2437, 2441, 2459, 2477, 2503, 2521, 2539, 2543, 2549, 2551, 2579, 2591, 2593, 2609, 2617, 2621, 2647, 2657, 2659, 2671, 2683, 2713, 2719, 2729, 2731, 2741, 2749, 2753, 2767, 2777, 2789, 2791, 2797, 2801, 2803, 2833, 2837, 2843, 2851, 2857, 2879, 2897, 2903, 2917, 2927, 2939, 2953, 2969, 2999, 3011, 3041, 3049, 3079, 3109, 3119, 3121, 3137, 3163, 3167, 3181, 3187, 3191, 3203, 3209, 3229, 3251, 3253, 3257, 3259, 3299, 3307, 3313, 3319, 3323, 3329, 3343, 3361, 3373, 3391, 3407, 3413, 3433, 3449, 3457, 3461, 3463, 3467, 3491, 3499, 3511, 3517, 3527, 3533, 3539, 3541, 3559, 3571, 3581, 3583, 3593, 3607, 3613, 3617, 3623, 3631, 3637, 3643, 3659, 3671, 3673, 3677, 3691, 3701, 3709, 3719, 3733, 3739, 3761, 3769, 3779, 3793, 3797, 3803, 3823, 3847, 3853, 3863, 3877, 3889, 3907, 3911, 3919, 3923, 3929, 3943, 3967, 3989, 4001, 4003, 4007, 4013, 4021, 4027, 4079, 4091, 4093, 4099, 4111, 4127, 4133, 4139, 4153, 4157, 4177, 4201, 4219, 4231, 4241, 4243, 4253, 4259, 4271, 4289, 4297, 4337, 4349, 4363, 4373, 4391, 4397, 4409, 4421, 4441, 4451, 4457, 4463, 4481, 4483, 4507, 4517, 4523, 4547, 4549, 4561, 4567, 4583, 4591, 4597, 4621, 4637, 4639, 4649, 4663, 4673, 4703, 4721, 4723, 4729, 4751, 4759, 4787, 4789, 4793, 4813, 4817, 4831, 4861, 4871, 4903, 4919, 4931, 4933, 4937, 4943, 4951, 4957, 4967, 4969, 4987, 4993, 4999, 5011, 5023, 5051, 5059, 5077, 5081, 5099, 5101, 5107, 5147, 5167, 5179, 5189, 5209, 5227, 5231, 5233, 5279, 5297, 5309, 5323, 5333, 5381, 5387, 5407, 5413, 5417, 5419, 5431, 5437, 5441, 5477, 5483, 5507, 5519, 5521, 5527, 5557, 5563, 5573, 5623, 5639, 5651, 5653, 5669, 5683, 5689, 5693, 5701, 5711, 5717, 5737, 5741, 5749, 5783, 5791, 5801, 5807, 5821, 5827, 5839, 5843, 5849, 5851, 5861, 5869, 5881, 5903, 5939, 5953, 5981, 6007, 6029, 6047, 6053, 6067, 6073, 6079, 6089, 6091, 6101, 6113, 6133, 6143, 6151, 6173, 6199, 6203, 6211, 6217, 6221, 6247, 6269, 6277, 6287, 6299, 6311, 6323, 6329, 6337, 6343, 6353, 6359, 6361, 6367, 6373, 6379, 6389, 6397, 6421, 6451, 6481, 6529, 6547, 6551, 6553, 6563, 6569, 6571, 6577, 6581, 6599, 6607, 6619, 6637, 6661, 6673, 6679, 6701, 6709, 6719, 6737, 6761, 6779, 6793, 6823, 6827, 6833, 6841, 6863, 6871, 6883, 6899, 6907, 6911, 6917, 6947, 6949, 6959, 6961, 6967, 6971, 6991, 7001, 7013, 7019, 7039, 7043, 7057, 7069, 7079, 7103, 7121, 7127, 7177, 7193, 7207, 7211, 7213, 7229, 7237, 7297, 7321, 7331, 7333, 7349, 7351, 7369, 7411, 7433, 7451, 7457, 7477, 7487, 7499, 7517, 7523, 7537, 7541, 7559, 7561, 7577, 7583, 7589, 7603, 7607, 7621, 7649, 7669, 7673, 7691, 7699, 7717, 7741, 7757, 7789, 7817, 7823, 7829, 7853, 7867, 7873, 7877, 7883, 7919, 7927, 7933, 7937, 7949, 7951, 7963, 7993, 8017, 8053, 8059, 8069, 8081, 8087, 8093, 8111, 8117, 8123, 8147, 8161, 8171, 8179, 8191, 8219, 8231, 8243, 8263, 8269, 8273, 8287, 8291, 8293, 8311, 8317, 8329, 8353, 8363, 8369, 8377, 8387, 8389, 8419, 8423, 8443, 8447, 8461, 8467, 8513, 8521, 8527, 8543, 8563, 8573, 8597, 8599, 8609, 8623, 8629, 8641, 8663, 8669, 8677, 8681, 8689, 8693, 8707, 8719, 8731, 8737, 8741, 8747, 8753, 8761, 8803, 8807, 8819, 8821, 8839, 8849, 8861, 8863, 8887, 8893, 8923, 8929, 8951, 8971, 9001, 9011, 9041, 9043, 9049, 9059, 9091, 9103, 9127, 9137, 9151, 9161, 9173, 9181, 9187, 9199, 9203, 9209, 9227, 9239, 9257, 9281, 9283, 9293, 9311, 9319, 9323, 9341, 9349, 9371, 9377, 9391, 9413, 9419, 9421, 9431, 9433, 9437, 9461, 9463, 9467, 9473, 9479, 9491, 9511, 9521, 9533, 9539, 9547, 9587, 9613, 9619, 9631, 9643, 9649, 9677, 9679, 9697, 9719, 9721, 9743, 9749, 9767, 9781, 9787, 9791, 9803, 9811, 9817, 9829, 9833, 9851, 9871, 9901, 9907, 9929, 9941, 9949, 9973];

/*best_d := 100000;
for i -> bas in bases do
  d, ranks := compute_d(X, bas, M, mws_primes);
  printf "bas #%o: d = %o\n\n", i, d;
  if forall{rank : rank in ranks | rank ge gX} then 
    if d lt best_d then 
      best_bas := bas;
      best_d := d;
      if d eq 1 then 
        break;
      end if;
    end if;
  end if;
end for;
d := best_d;*/
d := 1;
best_bas := bases[1];
bas := best_bas;

function run_QC(p, N1, N2)
  assert N1 ge N2;

  try
    //splitting_generators, divisors, intersections, splitting_indices, odd_divisors_Qp := height_init_g2(X, p, bas: N := N1, multiple_bound := 40); 
    printf "Computing Coleman data with N1 = %o.\n", N1;
    data := coleman_data(Q, p, N1 : useU := false);

    printf "\nStarting quadratic Chabauty for p = %o.\n", p;
    R<x> := PolynomialRing(Rationals());
    corrs := StarQuotientGoodCorrespondences(187, [p]);
    polys := corrs[1];
    time good_affine_rat_pts_xy, no_fake_pts, bad_affine_rat_pts_xy, data, fake_rat_pts, bad_Qppoints := QCModAffine(Q, p : use_polys := polys,
        number_of_correspondences := #polys-1, printlevel:=1, N := N1, prec := 40, base_point := base_pt);
    printf "There are %o fake rational points: %o\n", #fake_rat_pts, fake_rat_pts;
    printf "There are %o bad Q_%o-points.\n", #bad_Qppoints, p;

    function recompute_Coleman_data(N1, N2, fake_rat_pts)
      try
        // BUG: recompute Coleman data
        // Here * good_affine_rat_pts_xy contains the found rational points in disks where the Frob lift is defined 
        //      * no_fake_pts is true iff the solutions are exactly the rational points
        //      * bad_affine_rat_pts_xy contains the found rational points in disks where the Frob lift isn't defined 
        //      * data is the Coleman data of X at p used in the qc computation
        //      * fake_rat_pts contains the p-adic solutions that don't look rational
        //      * bad_Qppoints contains the disks where Frob isn't defined
        //
        // Express the images of the solutions under Abel-Jacobi in terms of the generators mod p^N
        fake_rat_pts_new := [];
        for i in [1..#fake_rat_pts] do
          fake_rat_pts_new[i] := [ChangePrecision(fake_rat_pts[i,j], N2) : j in [1..2]]; // N2 div 2
          // lower precision for speed and to avoid issues in Coleman integrals.
        end for;
        printf "Re-computing Coleman data with N2 = %o.\n", N2;
        data := coleman_data(Q, p, N2 : useU := false);

        fake_coeffs_mod_pN, rat_coeffs_mod_pN := coefficients_mod_pN(fake_rat_pts_new, good_affine_rat_pts_xy, divisors, base_pt, splitting_indices, data : printlevel := 3); 
        // Check that the coefficients of the known rational points are correct.
        //assert &and[&+[rat_coeffs_mod_pN[j,i] * bas[i] : i in [1..gX]] eq X!good_affine_rat_pts_xy[j] - X!base_pt : j in [1..#good_affine_rat_pts_xy]];
      catch e 
        printf "%o\n", e;
        if N2 lt N1 then
          N2 +:= 1;
        else 
          error "reached N2 = N1";
        end if;
        printf "trying N1 = %o, N2 = %o ...\n", N1, N2;
        return $$(N1, N2, fake_rat_pts);
      end try;
      return fake_coeffs_mod_pN, rat_coeffs_mod_pN;
    end function;

    fake_coeffs_mod_pN, rat_coeffs_mod_pN := recompute_Coleman_data(N1, N2, fake_rat_pts);
  catch e
    N1 +:= 1;
    return $$(primes, N1, 3);
  end try;
  
  return fake_coeffs_mod_pN, rat_coeffs_mod_pN;
end function;

fake_coeffs := [];
rat_coeffs := [];
for p in primes do
  fake_coeffs_mod_pN, rat_coeffs_mod_pN := run_QC(p, 20, 8);
  Append(~fake_coeffs, [fake_coeffs_mod_pN]);
  Append(~rat_coeffs, [rat_coeffs_mod_pN]);
end for;

print "done.";



load "src/mws_qc.m";
pts := [ptsX[i] : i in [1..#ptsX] | i ne index_of_base_point];
base_point := ptsX[index_of_base_point];

printf "\nUse the Mordell-Weil sieve to show that the additional %o solutions aren't rational.\n", [#fake_coeffs_mod_pN[1] : fake_coeffs_mod_pN in fake_coeffs];
printf "generating cosets ...\n";
qc_fake_coeffs_mod_M := coeffs_CRT(fake_coeffs, primes, exponents);
printf "number of cosets: %o\n", #qc_fake_coeffs_mod_M;
printf "adding information modulo %o\n", aux_int;
fake_coeffs_mod_M := combine_fake_good(qc_fake_coeffs_mod_M, qc_M, aux_int);
M := qc_M*aux_int; // modulus
qc_rat_coeffs_mod_M := [];
for i in [1..#ptsX] do
  //ptJ := X!pt - X!base_pt;
  //Append(~qc_rat_coeffs_mod_M, [t mod M : t in Eltseq(ptJ@@mMW)]);
  Append(~qc_rat_coeffs_mod_M, [0 : j in [1..i-1]] cat [1] cat [0 : j in [i+1..gX]]);
end for;
printf "number of cosets: %o\n", #fake_coeffs_mod_M;
printf "sieving with M = %o, S = %o\n", M, mws_primes;
//printf "gcd(#J(F_ell), #J(F_q)) (ell in S, q | MM') = %o\n", Gcd([#BaseChange(J, GF(v)) : v in mws_primes cat PrimeDivisors(M)]);
//factored_orders := [FactoredOrder(BaseChange(J, GF(v))) : v in mws_primes];
//printf "with [#J(F_v) : v in S] = %o\nand gcd_v(#J(F_v)) = %o\n", factored_orders, Factorization(Gcd([#BaseChange(J, GF(v)) : v in mws_primes]));

printf "starting Mordell Weil sieve\n";
time done_fake := MWSieve(X, mws_primes, M, bas, base_point, fake_coeffs_mod_M : 
  known_rat_coeffs := qc_rat_coeffs_mod_M, d := d, excluded := PrimeDivisors(N) cat [7, 457], SmoothBound := 77963257526, printlevel := 0);

printf "done with the MW sieve: %o\n", done_fake;
assert done_fake;
printf "No additional solutions are rational.\n";